apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx1
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
      name: my-pod
    spec:
      containers:
        - name: nginx1
          image: nginxinc/nginx-unprivileged
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1
  name: myservice
spec:
  selector:
    app: nginx1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---      
